version: "2"
services:
  redis:
    image: redis:alpine
    container_name: storage-redis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - $PWD/redis/.env

volumes:
  redis_data: