version: "2"
services:
  redis:
    image: redis:alpine
    container_name: storage-redis
    ports:
      - 6380:6379
    volumes:
      - $PWD/data/redis:/var/lib/redis
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - $PWD/redis/.env
  mongodb:
    image: mongo:latest
    container_name: storage-mongodb
    volumes:
      - $PWD/data/mongodb/:/data/db/
      - $PWD/data/log/mongodb/:/var/log/mongodb/
    environment:
      MONGO_INITDB_DATABASE: storage-db
    ports:
      - 27018:27017
  api:
    build: ./api
    command: yarn start
    container_name: storage-api
    volumes:
      - $PWD/api:/app/
      - /app/node_modules
    ports:
      - 1337:1337
    depends_on:
      - mongodb
      - redis
    env_file:
      - $PWD/api/.env
  dashboard:
    image: yongjhih/parse-dashboard
    container_name: storage-dashboard
    env_file:
      - $PWD/api/.dashboard.env
    ports:
      - 4040:4040
    depends_on:
      - api
  api-doc:
    image: slatedocs/slate:latest
    command: serve
    container_name: storage-api-doc
    volumes:
      - $PWD/api-doc/images/logo.png:/srv/slate/source/images/logo.png
      - $PWD/api-doc/index.html.md:/srv/slate/source/index.html.md
      - $PWD/api-doc/includes:/srv/slate/source/includes
      - $PWD/api-doc/build:/srv/slate/build
    ports:
      - 4567:4567
