version: "2"
services:
  postgres:
    image: postgis/postgis:9.6-2.5
    container_name: storage-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: storage-db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: developer
volumes:
  postgres_data:
