version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: storage-mongodb
    volumes:
      - $PWD/data/mongodb/:/data/db/
      - $PWD/data/log/mongodb/:/var/log/mongodb/
    environment:
      MONGO_INITDB_DATABASE: storage-db
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: secret