apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: storage-redis
  name: storage-redis
spec:
  ports:
  - name: "7372"
    port: 7372
    targetPort: 6379
  selector:
    io.kompose.service: storage-redis
status:
  loadBalancer: {}
