apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: storage-api
  name: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: storage-api
    spec:
      containers:
        - args:
            - yarn
            - start
          env:
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: APP_ID
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: DATABASE_URI
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: MASTER_KEY
            - name: PUBLIC_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: PUBLIC_SERVER_URL
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: REDIS_URI
            - name: RESTAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: RESTAPI_KEY
            - name: SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: storage-api-secrets
                  key: SERVER_URL
          image: raihan2006i/storage_api:1.0
          imagePullPolicy: "Always"
          name: storage-api
          ports:
            - containerPort: 1337
          resources: {}
      restartPolicy: Always
status: {}
