apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: storage-mongodb
  name: storage-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage-mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: storage-mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: storage-mongodb-secrets
              key: MONGO_INITDB_DATABASE
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: storage-mongodb-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storage-mongodb-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        image: mongo:latest
        imagePullPolicy: "Always"
        name: storage-mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
