apiVersion: v1
stringData:
  MONGO_INITDB_DATABASE: "storage-db"
  MONGO_INITDB_ROOT_USERNAME: "developer"
  MONGO_INITDB_ROOT_PASSWORD: "secret"
kind: Secret
metadata:
  name: storage-mongodb-secrets
type: Opaque
